conf.py:
  copyright: Copyright since 2016 by Daniel Siepmann
  project: Form PostProcessor for DB Inserts
  version: 1.1.0
  release: 1.1.0
  intersphinx_mapping:
    t3api:
      - https://typo3.org/api/typo3cms/
      - null
  html_theme_options:
    github_repository: web-vision/wv_form_db_insert
    github_branch: master
